var sweety="Sweeety";
var cutie="Cutie";
console.log("-----------Before swap-------------");
console.log(sweety, cutie);
var temp=sweety;
sweety=cutie;
cutie=temp;
console.log("-----------After swap--------------");
console.log(sweety,cutie);
console.log("===================================");
var num1=100, num2=200, num3=300;
console.log("-----------Before swap-------------");
console.log(num1,num2,num3);
console.log("-----------After swap--------------");
var temp=num1;
num1=num2;
num2=num3;
num3=temp;
console.log("-----------Before swap-------------");
console.log(num1,num2,num3);

